# Generated by Django 4.0.6 on 2022-11-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sogebank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('solde', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
    ]
